### ISSUE TITLE
Sign info and writable / written book info

### ISSUE THREAD

**Issue by Endermanbugzjfc** [SOF3/InfoAPI#24]
They should be convertible between item / block info, right? At least from item / block info to sign / book info so the new logic can be implemented without editing existing PHP code.
# What they contain
`text` string info.
# Off-topic
Got the idea when attempting and failing to implement sign shop with [Mineflow](https://github.com/aieuo/Mineflow). However, tbh, sign should should never be implemented with Mineflow. But a plugin instead. Time to upgrade [EconomyCShop](https://github.com/famima65536/EconomyCShop).

**Comment by SOF3** [comment]
signs are such an ancient thing... people used it because they didn't have custom forms, and in earlier days, when they didn't even have the chat button in MCPE 0.6.5 . Why on earth would you want to create a UI using sign as input?

**Comment by Endermanbugzjfc** [comment]
Right, if a code provides sign / book as info. They should also provide their text.

**Comment by SOF3** [comment]
I just don't understand your use case. Why would user want to display the text?

**Comment by Endermanbugzjfc** [comment]
> I just don't understand your use case. Why would user want to display the text?

It is not for display, it is for Mineflow. Remember I said I want to make Mineflow support infos?

**Comment by SOF3** [comment]
alright, I suppose InfoAPI can be used in the more general scenario of arbitrary infos.
