### ISSUE TITLE
Anonymous context does not fallback to base context.

### ISSUE THREAD

**Issue by Endermanbugzjfc** [SOF3/InfoAPI#30]
# Reproduce
1. Use an arbitrary plugin that contains `InfoAPI::render()`. *E.g. [ProfanityFilter](https://poggit.pmmp.io/p/ProfanityFilter)*
2. Compose a template which involves the base context.

Expectation: **everything would be rendered.**
Reality: **the anonymous info gets rendered while the base context info remains unchanged.**

# Attachments
## config.yml (portion)
```yml
block-warning-message: "&e{player_name} {baseContext.darkBlue} {infoapi.baseContext.playerCount} {infoapi.worldCount} &cwas blocked message contains profanity message."
```
## Log (portion)
```
[19:46:40.887] [Server thread/WARNING]: [ProfanityFilter] BlahCoast30765 {baseContext.darkBlue} {infoapi.baseContext.playerCount} {infoapi.worldCount} was blocked message contains profanity message.
```
## Corresponding code executed
https://github.com/ReinfyTeam/ProfanityFilter/blob/21f20fd74eb4c5ece7e54f69088c24d34fedfba1/src/EventListener.php#L76-L79
# Environment
InfoAPI: [**2.0.0-beta1**](https://github.com/ReinfyTeam/ProfanityFilter/blob/21f20fd74eb4c5ece7e54f69088c24d34fedfba1/composer.json#L11C10-L11C10)
PocketMine-MP: **5.4.3**

**Comment by Endermanbugzjfc** [comment]
The plugin virtually does not use InfoAPI.

**Comment by SOF3** [comment]
what do you mean?

**Comment by Endermanbugzjfc** [comment]
> what do you mean?

I think he reverted your PR at some point.

**Comment by SOF3** [comment]
I didn't see any revert

**Comment by Endermanbugzjfc** [comment]
> I don't see any revert, only build tool changes

¯\_(ツ)_/¯
