### ISSUE TITLE
Cannot detect integer and boolean types

### ISSUE THREAD

**Issue by Aboshxm2** [SOF3/InfoAPI#31]
Code:
```php
$this->getLogger()->info(InfoAPI::render($this, "test {arg}", ["arg" => true]));
```
Crash:
[Mon_Nov_27-07.21.29-UTC_2023.log](https://github.com/SOF3/InfoAPI/files/13470973/Mon_Nov_27-07.21.29-UTC_2023.log)
---
After debugging the code it looks like when the [ReflectUtil tring to get the type of the clousre parameter](https://github.com/SOF3/InfoAPI/blob/master/lib/reflect.php#L88) for int/bool parameters, it gives different value than gettype function used [here](https://github.com/SOF3/InfoAPI/blob/master/lib/reflect.php#L233).
```php
$reflect = new ReflectionFunction(fn(int $p1, bool $p2) => "whatever");

$closureParams = $reflect->getParameters();

echo($closureParams[0]->getType());// int
echo "\n";
echo(gettype(123));// integer
echo "\n";
echo($closureParams[1]->getType());// bool
echo "\n";
echo(gettype(true));// boolean
```
---
Sorry for bad desigging the issue.

**Comment by Aboshxm2** [comment]
re-designing [getStandardType](https://github.com/SOF3/InfoAPI/blob/master/lib/reflect.php#L227) function like this fixes the issue.

```php
	public static function getStandardType(mixed $value) : string {
		if (is_float($value)) {
			// double -> float
			return "float";
		}
		if (is_int($value)) {
			// integer -> int
			return "int";
		}
		if (is_bool($value)) {
			// boolean -> bool
			return "bool";
		}

		return gettype($value);
	}
```

Can I make pr if you adopted this solution? 🙂

**Comment by SOF3** [comment]
sure, please send a pull request.
